---
- name: Controllers
  hosts: controllers
  tasks:
    - name: Copy Certs
      copy:
        src: ../certificates/{{ item }}
        dest: ~/{{ item }}
      with_items:
        - ca.pem
        - ca-key.pem
        - kubernetes-key.pem
        - kubernetes.pem
        - service-account-key.pem
        - service-account.pem
    - name: Copy kubeconfig
      copy:
        src: ../kubeconfig/{{ item }}
        dest: ~/{{ item }}
      with_items:
        - admin.kubeconfig
        - kube-controller-manager.kubeconfig
        - kube-scheduler.kubeconfig

- name: Worker
  hosts: workers
  tasks:
    - name: Copy Certs
      copy:
        src: ../certificates/{{ item }}
        dest: ~/{{ item }}
      with_items:
        - ca.pem
        - "{{ inventory_hostname }}.pem"
        - "{{ inventory_hostname }}-key.pem"
    - name: Copy kubeconfig
      copy:
        src: ../kubeconfig/{{ item }}
        dest: ~/{{ item }}
      with_items:
        - kube-proxy.kubeconfig
        - "{{ inventory_hostname }}.kubeconfig"
